[package]
name = "winograd-conv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.2"
num = "0.4.0"
polynomen = "1.0.0"
polynomial-ring = "0.5.0"
